"""Final forensic report generator (J3) — the headline evidence-anchored report.

Deterministic, code-built from the :class:`ReportView` (no LLM). Hard rules: every CONFIRMED finding
cites artifact + sha256 + tool + tool_call_id + confidence; UNSUPPORTED claims appear ONLY in their
appendix (never as fact — enforced by the view); the tool-execution appendix lists EVERY tool call
(uncapped); the LIMITATIONS section is mandatory ("NOT court-ready"). Every real-run edge case
(empty/halted run, retry-only tasks, escalations, failed tools, fell-back agents) degrades safely.
"""

from __future__ import annotations

from pathlib import Path

from siftmesh_core.reports.attack import attack_attribution, lookup, lookup_for_claim
from siftmesh_core.reports.loader import MAX_DETAILED_FINDINGS, ReportView, load_report_view
from siftmesh_core.reports.render import MarkdownBuilder, compose_report, fmt_float, write_report
from siftmesh_core.run_dir import RunPaths
from siftmesh_core.schemas.claim import Claim

_SHA_SHORT = 16
_NOT_COURT_READY = (
    "This report is generated by an automated triage system. It is **NOT a claim of court "
    "admissibility or forensic completeness**; findings are evidence-anchored leads for an analyst."
)


def generate_final_report(
    run: RunPaths, *, evidence_root: Path | str | None = None, view: ReportView | None = None
) -> Path:
    """Write ``reports/final_report.md`` from the run-dir ledgers; return its path."""
    v = view or load_report_view(run, evidence_root=evidence_root)
    md = MarkdownBuilder()
    md.h1(f"SIFTMesh Forensic Report — {v.run_id}")

    _exec_summary(md, v)
    _objective_answer(md, v)
    _scope(md, v)
    _methodology(md, v)
    _timeline(md, v)
    _findings(md, v, "Confirmed findings", v.confirmed, labelled=False)
    _findings(md, v, "Inferred findings (lower confidence)", v.inferred, labelled=True)
    _attack(md, v)
    _contradictions(md, v)
    _self_correction(md, v)
    _custody(md, v)
    _tool_appendix(md, v)
    _unsupported_appendix(md, v)
    _injection(md, v)
    _limitations(md, v)

    text = compose_report(
        run_id=v.run_id, run_root=v.run_root, body=md.build(), load_errors=v.load_errors
    )
    return write_report(run, "final_report.md", text, evidence_root=evidence_root)


# ── sections ───────────────────────────────────────────────────────────────────


def _exec_summary(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Executive summary")
    if not v.has_execution:
        status = _run_status(v)
        md.line(
            f"No analytic execution recorded for this run ({status}). "
            "Evidence was sealed but no findings were produced."
        )
        return
    md.bullet(f"Confirmed findings: {len(v.confirmed)}")
    md.bullet(f"Inferred findings: {len(v.inferred)}")
    if v.contradicted:
        md.bullet(f"Contradicted claims: {len(v.contradicted)}")
    md.bullet(f"Unsupported claims (rejected, not facts): {len(v.unsupported)}")
    md.bullet(f"Contradictions detected: {len(v.contradictions)}")
    md.bullet(f"Self-correction retries: {len(v.retries)}")
    md.bullet(f"Prompt-injection alerts (logged, not executed): {len(v.injection_alerts)}")
    if v.verdict_tally:
        tally = ", ".join(f"{k}={n}" for k, n in v.verdict_tally.items())
        md.bullet(f"Critic verdicts: {tally}")
    md.bullet(f"Run status: {_run_status(v)}")


def _run_status(v: ReportView) -> str:
    if v.run_state is None:
        return "driven by discrete CLI commands (no engine snapshot)"
    rs = v.run_state
    if rs.blocked_gate:
        return f"halted awaiting approval at the '{rs.blocked_gate}' gate"
    if rs.terminal and rs.state != "done":
        return f"terminated in state '{rs.state}'"
    return f"state={rs.state}, mode={rs.mode}, iteration={rs.iteration}/{rs.max_iterations}"


def _objective_answer(md: MarkdownBuilder, v: ReportView) -> None:
    """Answer the operator's incident objective from the PROMOTED (anchored) findings only.

    Deterministic, no LLM: it quotes the objective and re-presents the already-promoted
    confirmed/inferred claims that bear on it. It NEVER reads unsupported claims (the
    unsupported-only-in-appendix firewall holds), and emits nothing when no --brief was given.
    """
    objective = v.manifest.incident_objective if v.manifest is not None else None
    if not objective:
        return
    md.h2("Answer to the incident objective")
    md.line("**Operator objective:**")
    md.bullet(_truncate(objective, 280))
    findings = [c for c in v.high_signal_claims if c in (*v.confirmed, *v.inferred)]
    if not findings:
        md.blank().line(
            "No evidence-anchored finding yet bears on this objective. See the limitations and "
            "the follow-up/coverage notes below."
        )
        return
    md.blank().line(
        f"{len(v.confirmed) + len(v.inferred)} evidence-anchored finding(s) bear on the objective; "
        f"the highest-signal are listed here (full set under Findings):"
    )
    for c in findings:
        md.blank().line(f"**{c.claim_id}** — {c.claim}")
        md.bullet(
            f"artifact `{c.source_artifact}` · sha256 `{(c.source_sha256 or '')[:_SHA_SHORT]}…` · "
            f"tool `{c.tool_name}` · call `{c.tool_call_id}` · confidence {_confidence(v, c)}"
        )


def _scope(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Scope & case metadata")
    if v.manifest is None:
        md.line("No evidence manifest present (run not sealed).")
        return
    m = v.manifest
    md.bullet(f"Case: {m.case_id}")
    md.bullet(f"Run: {m.run_id}")
    md.bullet(f"Sealed (UTC): {m.created_utc}")
    md.bullet(f"Evidence artifacts: {len(m.files)}")
    md.bullet(f"SIFTMesh tool version: {m.tool_version}")


def _methodology(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Methodology & tools")
    if not v.tool_results:
        md.line("No typed tools were invoked.")
        return
    seen: dict[tuple[str, str], int] = {}
    for t in v.tool_results:
        seen[(t.tool_name, t.backend)] = seen.get((t.tool_name, t.backend), 0) + 1
    md.table(
        ["Tool", "Backend", "Invocations"],
        [[name, backend, str(n)] for (name, backend), n in sorted(seen.items())],
    )
    failed = [t for t in v.tool_results if t.status != "success"]
    if failed:
        md.blank().line(f"**{len(failed)} tool invocation(s) failed** (partial coverage):")
        for t in failed:
            md.bullet(
                f"`{t.tool_call_id}` {t.tool_name} on `{t.source_artifact}` — {t.status}"
                f" ({t.error_code or 'no code'})"
            )


def _timeline(md: MarkdownBuilder, v: ReportView) -> None:
    dated = sorted(
        (c for c in (*v.confirmed, *v.inferred) if c.timestamp_utc is not None),
        key=lambda c: (str(c.timestamp_utc), c.claim_id),
    )
    if not dated:
        return
    md.h2("Timeline of events (UTC)")
    rows = [
        [str(c.timestamp_utc), c.status, _truncate(c.claim, 90)]
        for c in dated[:MAX_DETAILED_FINDINGS]
    ]
    md.table(["Timestamp", "Status", "Event"], rows)
    if len(dated) > MAX_DETAILED_FINDINGS:
        md.line(f"_… {len(dated) - MAX_DETAILED_FINDINGS} more timestamped findings._")


def _findings(
    md: MarkdownBuilder, v: ReportView, title: str, claims: tuple[Claim, ...], *, labelled: bool
) -> None:
    md.h2(title)
    if not claims:
        md.line("None.")
        return
    shown = [c for c in v.high_signal_claims if c in claims][:MAX_DETAILED_FINDINGS]
    if not shown:  # high_signal is confirmed+inferred ranked; fall back to head of this list
        shown = list(claims[:MAX_DETAILED_FINDINGS])
    for c in shown:
        md.blank().line(f"**{c.claim_id}** — {c.claim}")
        atk = lookup_for_claim(c)
        anchor = (
            f"artifact `{c.source_artifact}` · sha256 `{(c.source_sha256 or '')[:_SHA_SHORT]}…` · "
            f"tool `{c.tool_name}` · call `{c.tool_call_id}` · confidence {_confidence(v, c)}"
        )
        if labelled:
            anchor = "INFERRED · " + anchor
        md.bullet(anchor)
        if atk:
            md.bullet(f"ATT&CK: {atk.tactic} / {atk.id_display} {atk.name}")
        if c.claim_id in v.claims_on_failed_tools:
            md.bullet("⚠ anchored to a tool call that did not fully succeed — verify manually")
        if c.requires_human_review:
            md.bullet("⚠ flagged for human review")
    if len(claims) > len(shown):
        md.blank().line(
            f"_… {len(claims) - len(shown)} additional finding(s) of this class "
            "(full set in claims/claim_ledger.jsonl)._"
        )
        by_type = {t: n for t, n in v.findings_by_evidence_type.items()}
        if by_type:
            md.line("Counts by evidence type: " + ", ".join(f"{t}={n}" for t, n in by_type.items()))


def _attack(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("MITRE ATT&CK mapping")
    findings = (*v.confirmed, *v.inferred)
    if not findings:
        md.line("No findings to map.")
        return
    counts: dict[str, int] = {}
    for c in findings:
        counts[c.evidence_type] = counts.get(c.evidence_type, 0) + 1
    rows = []
    for etype, n in sorted(counts.items()):
        atk = lookup(etype)
        if atk is None:
            rows.append([etype, "(unmapped)", "—", str(n)])
        else:
            rows.append([etype, f"{atk.tactic} / {atk.id_display}", atk.name, str(n)])
    md.table(["Evidence type", "Tactic / Technique", "Name", "Claims"], rows)
    md.line(f"_ATT&CK reference: {attack_attribution()}._")


def _contradictions(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Contradictions & resolution")
    if not v.contradictions:
        md.line("None detected.")
        return
    md.table(
        ["ID", "Rule", "Subject", "Detail"],
        [
            [x.contradiction_id, x.rule, _truncate(x.subject, 40), _truncate(x.detail, 80)]
            for x in v.contradictions
        ],
    )
    md.line("_Contradictions escalate for human resolution; neither side is reported as fact._")


def _self_correction(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Self-correction & retries")
    retry_only = sorted(
        t for t, vd in v.verdict_by_task_id.items() if vd.verdict == "retry_required"
    )
    fell_back = [a for a in v.agent_calls if a.status == "fell_back"]
    errored = [a for a in v.agent_calls if a.status in ("error", "retry_required")]
    if not (v.retries or retry_only or fell_back or errored):
        md.line("No self-correction events recorded.")
        return
    if v.retries:
        md.line("**Retry events** (critic rejected → tightened contract → re-dispatch):")
        for r in v.retries:
            crit = "; ".join(r.tightened_criteria) if r.tightened_criteria else r.cause
            hop = f"a{r.from_attempt}->a{r.to_attempt}"
            md.bullet(f"`{r.retry_id}` {r.task_id} {hop}: {_truncate(crit, 70)}")
    if retry_only:
        md.blank().bullet(
            f"Tasks still requiring retry (no accepted claim): {', '.join(retry_only)}"
        )
    if fell_back:
        md.blank().line(
            "**Adapter fall-backs** (requested live agent unavailable → deterministic floor):"
        )
        for a in fell_back:
            md.bullet(
                f"{a.task_id}: requested `{a.fell_back_from or a.profile}` → ran `{a.adapter}`"
            )
    if errored:
        md.blank().line("**Agent errors/timeouts:**")
        for a in errored:
            md.bullet(f"{a.task_id}: `{a.adapter}` status={a.status}")


def _custody(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Chain of custody")
    if not v.custody:
        md.line("No custody events recorded.")
        return
    md.table(
        ["Artifact", "sha256", "Action", "Actor", "Tool", "Result"],
        [
            [
                _truncate(e.artifact, 40),
                e.source_sha256[:_SHA_SHORT] + "…",
                e.action,
                e.actor,
                e.tool_name,
                e.result,
            ]
            for e in v.custody[:MAX_DETAILED_FINDINGS]
        ],
    )
    if len(v.custody) > MAX_DETAILED_FINDINGS:
        md.line(f"_… {len(v.custody) - MAX_DETAILED_FINDINGS} more custody events._")


def _tool_appendix(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Appendix A — tool-execution log (complete)")
    if not v.tool_results:
        md.line("No tool calls.")
        return
    md.table(
        ["tool_call_id", "Tool", "Source artifact", "source_sha256", "Status", "Code"],
        [
            [
                t.tool_call_id,
                t.tool_name,
                _truncate(t.source_artifact, 44),
                t.source_sha256,
                t.status,
                t.error_code or "—",
            ]
            for t in v.tool_results
        ],  # NEVER capped — full traceability
    )


def _unsupported_appendix(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Appendix B — unsupported claims (rejected, NOT findings)")
    if not v.unsupported:
        md.line("None — every recorded claim was evidence-anchored.")
        return
    md.line("_These claims lacked a verifiable evidence anchor and are excluded from findings._")
    md.table(
        ["claim_id", "Claim", "Why rejected"],
        [[c.claim_id, _truncate(c.claim, 80), _why_unsupported(c)] for c in v.unsupported],
    )


def _injection(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Appendix C — prompt-injection alerts (hostile-evidence handling)")
    if not v.injection_alerts:
        md.line("None.")
        return
    md.line("_Evidence is treated as data, never instructions; these were logged, never executed._")
    md.table(
        ["alert_id", "Source", "Signature", "Snippet"],
        [
            [
                a.alert_id,
                a.source,
                a.signature,
                "`" + _truncate(a.snippet.replace("`", "'"), 60) + "`",
            ]
            for a in v.injection_alerts
        ],
    )


def _limitations(md: MarkdownBuilder, v: ReportView) -> None:
    md.h2("Limitations & assumptions")
    md.bullet(_NOT_COURT_READY)
    md.bullet("Timestamps are interpreted and reported in UTC.")
    md.bullet("Evidence is treated as hostile: filenames and content are data, never instructions.")
    if v.unsupported:
        md.bullet(
            f"{len(v.unsupported)} agent claim(s) were rejected for lack of evidence (Appendix B)."
        )
    if v.claims_on_failed_tools:
        md.bullet(
            f"{len(v.claims_on_failed_tools)} finding(s) are anchored to a tool call that did not "
            "fully succeed — verify manually."
        )
    unmapped = sorted(
        {c.evidence_type for c in (*v.confirmed, *v.inferred) if lookup(c.evidence_type) is None}
    )
    if unmapped:
        md.bullet(f"Evidence types without an ATT&CK mapping: {', '.join(unmapped)}.")
    if v.manifest is not None:
        examined = {c.source_artifact for c in (*v.confirmed, *v.inferred) if c.source_artifact}
        uncovered = sorted(f.path for f in v.manifest.files if f.path not in examined)
        if uncovered:
            md.bullet(f"{len(uncovered)} manifest artifact(s) produced no finding (coverage gap).")
    for err in v.load_errors:
        md.bullet(f"Load note: {err}")


# ── helpers ────────────────────────────────────────────────────────────────────


def _confidence(v: ReportView, c: Claim) -> str:
    if c.claim_id in v.confidence_by_claim_id:
        original, final = v.confidence_by_claim_id[c.claim_id]
        return f"{fmt_float(original)} → {fmt_float(final)}"
    return fmt_float(c.confidence)


def _why_unsupported(c: Claim) -> str:
    missing = [
        f
        for f in ("source_artifact", "source_sha256", "tool_name", "tool_call_id")
        if not getattr(c, f)
    ]
    return "missing " + ", ".join(missing) if missing else "agent assertion without evidence"


def _truncate(text: str, limit: int) -> str:
    text = text.replace("\n", " ").replace("|", "\\|").strip()
    return text if len(text) <= limit else text[: limit - 1] + "…"
